MAN_PAGES = {
    "ls": "ls [-la] [path] - list directory contents. -l long format, -a show hidden files.",
    "cd": "cd [path] - change the current directory. 'cd ..' goes up one level.",
    "pwd": "pwd - print the full path of the current working directory.",
    "cat": "cat <file> - print a file's contents to the screen.",
    "mkdir": "mkdir [-p] <dir> - create a new directory. -p creates parent dirs as needed.",
    "touch": "touch <file> - create an empty file (or update its timestamp).",
    "rm": "rm [-r] <path> - delete a file. -r deletes a directory recursively.",
    "cp": "cp <src> <dst> - copy a file.",
    "mv": "mv <src> <dst> - move or rename a file or directory.",
    "chmod": "chmod <mode> <path> - change permissions, e.g. chmod 755 file or chmod +x file.",
    "chown": "chown <user> <path> - change the owner of a file.",
    "find": "find <path> -name <pattern> - search for files matching a name pattern.",
    "grep": "grep [-r] [-i] [-n] <pattern> <path> - search for text inside files.",
    "echo": "echo <text> [> file | >> file] - print text, optionally redirecting to a file.",
    "head": "head [-n N] <file> - print the first N lines of a file (default 10).",
    "tail": "tail [-n N] <file> - print the last N lines of a file (default 10).",
    "wc": "wc [-l] <file> - count lines/words/characters in a file.",
    "whoami": "whoami - print the current user name.",
    "id": "id - print user and group id information.",
    "ps": "ps [aux] - list running processes.",
    "top": "top - display a live-ish snapshot of running processes and load.",
    "kill": "kill <pid> - terminate a process by its process id.",
    "df": "df -h - show disk space usage.",
    "du": "du -h <path> - show file/directory size usage.",
    "sudo": "sudo <command> - run a command with root privileges.",
    "history": "history - show previously entered commands.",
    "ifconfig": "ifconfig / ip a - show network interfaces and their IP addresses.",
    "ping": "ping <host> - send ICMP echo requests to test reachability of a host.",
    "netstat": "netstat -tulnp / ss -tulnp - show listening ports and services on this machine.",
    "curl": "curl <url> - fetch the contents of a URL over HTTP.",
    "wget": "wget <url> - download the contents of a URL.",
    "dig": "dig <domain> / nslookup <domain> - resolve a domain name to an IP address.",
    "traceroute": "traceroute <host> - show the network hops to reach a host.",
    "nmap": "nmap <host> - scan a host for open ports and running services.",
    "ssh": "ssh user@host - open a remote shell session on another machine.",
    "exit": "exit - close the current ssh session, or quit the game if at the local machine.",
}
